name: ChuckNorris
options:
  bundleIdPrefix: br.com.mentoria
  developmentLanguage: pt-BR
configs:
  dev: debug
  prod: release
  test: debug
targets:
  ChuckNorris:
    type: application
    platform: iOS
    deploymentTarget: '14.0'
    sources: [App]
    settings:
      base:
        INFOPLIST_FILE: App/Info.plist
  UnitTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: '14.0'
    sources:
      - path: App
        excludes:
          - UITests
    dependencies:
      - target: ChuckNorris
  UITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: UITests
    dependencies:
      - target: ChuckNorris
schemes:
  Dev:
    run:
      config: dev
    build:
      targets:
        ChuckNorris: all
    archive:
      config: dev
  Prod:
    run:
      config: prod
    build:
      targets:
        ChuckNorris: all
  UnitTests:
    build:
      targets:
        UnitTests: all
    test:
      config: dev
      targets:
        - ChuckNorris
      gatherCoverageData: true
  UITests:
    build:
      targets:
        UITests: [test]
    test:
      config: dev
      targets:
        - ChuckNorris
      gatherCoverageData: true
